#!/bin/bash
# Quick Start Guide for QuarryForce Local Development

echo "==========================================="
echo "QuarryForce Backend - Quick Start Guide"
echo "==========================================="
echo ""

echo "📋 CHECKLIST: What You Have"
echo "✅ Database: XAMPP MySQL with 5 tables"
echo "✅ Backend: Node.js Express server"
echo "✅ APIs: 11 endpoints ready"
echo "✅ Security: Device binding, GPS geofence"
echo ""

echo "🚀 STEP 1: Start XAMPP"
echo "1. Open XAMPP Control Panel"
echo "2. Click START next to MySQL (should turn green)"
echo "3. Click START next to Apache (should turn green)"
echo "4. Verify at: http://localhost/phpmyadmin"
echo ""

echo "🚀 STEP 2: Start Backend Server"
echo "$ cd d:\quarryforce"
echo "$ node index.js"
echo ""
echo "Expected output:"
echo "  🚀 QuarryForce Backend Server Started!"
echo "  📍 Server: http://localhost:3000"
echo ""

echo "🧪 STEP 3: Test Server (Choose One)"
echo ""
echo "Option A - Browser:"
echo "  Visit: http://localhost:3000/api/settings"
echo "  Should show JSON with company name & GPS radius"
echo ""
echo "Option B - Postman:"
echo "  1. Download Postman (free)"
echo "  2. Import: d:\quarryforce\postman_collection.json"
echo "  3. Try any endpoint"
echo ""
echo "Option C - cURL:"
echo "  $ curl http://localhost:3000/api/settings"
echo ""

echo "📝 STEP 4: Add Test Data (OPTIONAL)"
echo "If API keeps returning success but you want to test with data:"
echo "1. Open http://localhost/phpmyadmin"
echo "2. Select database 'quarryforce'"
echo "3. Click SQL tab"
echo "4. Copy contents of TEST_DATA.sql file"
echo "5. Paste into SQL box"
echo "6. Click Go"
echo ""

echo "📁 FILES CREATED"
echo "✅ index.js                 - Main server (11 APIs)"
echo "✅ db.js                    - Database connection"
echo "✅ .env                     - Database credentials"
echo "✅ package.json             - Node dependencies"
echo "✅ API_DOCUMENTATION.md     - Full API reference"
echo "✅ postman_collection.json  - For testing in Postman"
echo "✅ README.md                - Development guide"
echo "✅ TEST_DATA.sql            - Sample data for testing"
echo ""

echo "🎯 NEXT STEPS"
echo ""
echo "A. Continue Backend Development"
echo "   - Add file upload for photos"
echo "   - Add JWT authentication"
echo "   - Add real-time GPS tracking"
echo ""
echo "B. Start Mobile App (Flutter)"
echo "   - Create login screen"
echo "   - Create GPS map screen"
echo "   - Create camera screens"
echo "   - Connect to /api/login, /api/settings, /api/checkin"
echo ""
echo "C. Create Admin Dashboard (Web)"
echo "   - Display map with rep GPS pins"
echo "   - Show all visits today"
echo "   - Edit settings (GPS radius, company name)"
echo ""

echo "🔑 API ENDPOINTS"
echo "GET  /api/settings                - Get app config"
echo "POST /api/login                   - Device binding login"
echo "POST /api/checkin                 - GPS verification"
echo "POST /api/visit/submit            - Save completed visit"
echo "POST /api/fuel/submit             - Save fuel log"
echo "GET  /api/admin/reps              - List all reps"
echo "GET  /api/admin/customers         - List all customers"
echo "POST /api/admin/reset-device      - Unlock rep's phone"
echo ""

echo "🆘 TROUBLESHOOTING"
echo ""
echo "Q: Server won't start?"
echo "A: npm install geolib"
echo ""
echo "Q: Cannot connect to database?"
echo "A: Is MySQL running in XAMPP? (should be GREEN)"
echo ""
echo "Q: API returns empty error?"
echo "A: Check database credentials in .env file"
echo ""
echo "Q: Port 3000 already in use?"
echo "A: netstat -ano | findstr :3000"
echo "   taskkill /PID [NUMBER] /F"
echo ""

echo "=========================================="
echo "Ready to develop! Happy coding! 🚀"
echo "=========================================="
